### PR TITLE
Update dependencies and health files and fix linter problems

### PR DESCRIPTION
**Pull request by SethFalco**
### .github/ISSUE_TEMPLATE.md
* Removes Slack as this doesn't appear to be running. The link was also removed from the base metalsmith repository. (https://github.com/metalsmith/metalsmith/commit/0bea2ac0db47ebeab10e9c6a45653bf6eb7ee4ea)

### README.md
* Removes Greenkeeper as this is no longer active in favor of Snyk.

### lib/index.js
* Fixed linter problems introduced after updating dependencies. ([prefer-object-spread](https://eslint.org/docs/rules/prefer-object-spread))

### package.json
* Update all dependencies to their latest versions except `multimatch` which I only updated to 5.0.0. (Latest is 6.0.0)
  * Reduces vulnerabilities from `42 moderate severity vulnerabilities` to `5 moderate severity vulnerabilities`

---

Linting and tests all pass after these changes.

### CODE REVIEW

**Comment by webketje** [comment]
Thx @SethFalco,

I have 1 main poinrt before this can be merged:
- For the next release I'd like to keep Node >= 8 support. You can check dependency compatibility by running `npm info <pkg>@* engines.node`. Unfortunately the latest Node 8 compatible version for multimatch is 4.0.0, so that needs to be re-downgraded. For devDependecies the ones used in CI `npm test` need to be compatible with the environments they are used in. That means `jest@25.5.4` and possibly others. Others can be upgraded to latest.

Stackoverflow link can be `https`.
I don't really agree with the [ESlint rule](https://eslint.org/docs/rules/prefer-object-spread) but I don't mind following it.

**Comment by SethFalco** [comment]
Sure, I've added the following to the `package.json` also just to kind of document that requirement.
I'm not sure of npm will use it, but I know yarn would automatically check against the engines when installing dependencies.

```json
"engines": {
  "node": ">=8"
},
```


* I've downgrading dependencies to meet the `engine.node` field of dependencies.
* Replaced all `http` links with `https`.
* Removed a reference to the Slack channel from the README which I just noticed.

Just noting it since it's changed from the original PR summary:
Reduces vulnerabilities from `42 moderate severity vulnerabilities` to `21 vulnerabilities (18 moderate, 3 critical)`

**Comment by SethFalco** [comment]
The build fails because of the test task running with Node 6. If we're only supporting Node >= 8 I assume, could we just remove that and rerun this?

image

**Comment by webketje** [comment]
@SethFalco Correct, I'm in the process of upgrading the plugin repo's to a common setup and that will include the travis.yml currently already available at https://github.com/metalsmith/excerpts/blob/master/.travis.yml

**Pull request merged**
