### PR TITLE
Add suppressNoFilesError #160

### PR DESCRIPTION
**Pull request by mrhubbs**
This enables proper integration with incremental plugins like [metalsmith-watch](https://www.npmjs.com/package/metalsmith-watch).

### CODE REVIEW

**Comment by mrhubbs** [comment]
FYI @ismay

**Comment by ismay** [comment]
Thanks! Could you rebase on master? I pushed a commit that fixes the bug that caused your CI to fail. That way we can see if the tests pass with your changes.

**Comment by mrhubbs** [comment]
Ah okay. I tried to run the tests locally. They wouldn't run so I thought maybe I had some environment wrong. I've never used `jest` before.

I've added a test for the new behavior. All tests are passing on my machine.

**Comment by ismay** [comment]
Sorry it took a while, was a bit busy. Thanks for the PR!

**Comment by ismay** [comment]
Published with 2.2.0

**Comment by ismay** [comment]
Thanks! That’s good to hear 😊. Hadn’t heard of forge before, seems cool!

**Pull request merged**
